superjobs_user:
    resource: "@SuperjobsUserBundle/Resources/config/routing.yml"
    prefix:   /

superjobs_home:
    resource: "@SuperjobsHomeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
#
#genemu_base64:
#    resource: "@GenemuFormBundle/Resources/config/routing/base64.xml"
#
#genemu_upload:
#    resource: "@GenemuFormBundle/Resources/config/routing/upload.xml"