# superjobs_user_homepage:
#     path:     /
#     defaults: { _controller: SuperjobsUserBundle:Default:index }

recruiter_registration:
    path:  /register/recruiter
    defaults: { _controller: SuperjobsUserBundle:RegistrationRecruiter:register }

applicant_registration:
    path:  /register/applicant
    defaults: { _controller: SuperjobsUserBundle:RegistrationApplicant:register }